{
 "title": "Team-4 | Analytics Service",
 "tags": [
  "Service Health",
  "Business KPI"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Business KPIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events Consumed Total (Total)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "analytics_events_consumed_total",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Events/sec by Topic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "rate(analytics_events_consumed_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Event Processing Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(analytics_event_processing_latency_ms_bucket[5m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "InfluxDB Write Failures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "analytics_influx_writes_total{status=\"failure\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "rate(flask_http_request_total[1m])",
       "legendFormat": "{{method}} {{status}}"
      }
     ]
    },
    {
     "title": "HTTP Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "rate(flask_http_request_total{status=~\"4..| 5..\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P95 Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(flask_http_request_duration_seconds_bucket[5m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Service Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "time()- process_start_time_seconds",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}